### ISSUE TITLE
Github Campus Expert

### ISSUE THREAD

**Issue by Moiz-Zubair** [adilshehzad786/github-webinar#3]
Can you plz guide me about Github campus expert program, like how to apply, when to apply and what are the benefits

**Comment by adilshehzad786** [comment]
Apply: http://githubcampus.expert/
Currently, Applications are closed due to maintenance
Benefits 👍 💯 

`As a Campus Expert completes more training modules, they will gain access to more resources to use to help their community. Benefits range from free stickers and cheat sheets for your school, to event/hackathon sponsorships, to travel support to attend GitHub events and conferences.`

**Comment by Moiz-Zubair** [comment]
Can you tell me when will the applications will be opened, and what about the swags of the quiz that you took???

**Comment by adilshehzad786** [comment]
Date is not yet announced .
